# Generated by Django 5.0.7 on 2024-07-25 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservice',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomservice',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_services', to='hotels.hotel'),
        ),
        migrations.AlterField(
            model_name='service',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hotels.hotel'),
        ),
    ]
