# Generated by Django 5.0.7 on 2024-07-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotelregistereduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomservice',
            name='available',
        ),
        migrations.RemoveField(
            model_name='roomservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='roomservice',
            name='price',
        ),
    ]
