# Generated by Django 5.0.7 on 2024-07-26 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_remove_roomservice_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_reserved', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='hotels.service')),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.availabletime'),
        ),
    ]
