# Generated by Django 5.0.7 on 2024-07-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_availabletime_alter_reservation_reserved_for'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabletime',
            options={'verbose_name': 'Taken Date', 'verbose_name_plural': 'Taken Dates'},
        ),
    ]
